default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ky331144
  host: localhost

development:
  <<: *default
  database: asagao_development

test:
  <<: *default
  database: asagao_test

production:
  <<: *default
  database: asagao_production
